### ISSUE TITLE
`snippets/acquaintances.lua`: frequency does not update

### ISSUE THREAD

**Issue by joshuagoran** [monome/bowery#13]
within the `update_speeds` function, I am seeing `freq` remain a static value (`7.389056`, which is equal to `math.exp(2)`) no matter what voltage is present at input 1. 

I think this is due to some issue with line 21. `math.exp()` seems to expect one argument according to the Lua docs I am seeing ([example](http://math2.org/luasearch/math.html#math_exp)) and replit.com. the second argument is being ignored in the current script.

maybe this should be using a different `math` function?

**Comment by joshuagoran** [comment]
side note: I am super stoked to try this out in a fully working state! :)

**Comment by m9dfukc** [comment]
bumping this up ... stumbled into the same issue!

**Comment by dndrks** [comment]
@m9dfukc + @joshuagoran , thanks so much for the note! fix has been implemented :)
